import { Technology } from "../types/technology";

export const nameByTechnology: Record<Technology, string> = {
  [Technology.HTML]: "HTML",
  [Technology.CSS]: "CSS",
  [Technology.JAVASCRIPT]: "JavaScript",
  [Technology.TYPESCRIPT]: "TypeScript",
  [Technology.REACT]: "React",
  [Technology.REACT_NATIVE]: "React Native",
  [Technology.NEXT_JS]: "Next.js",
  [Technology.NODE_JS]: "Node.js",
  [Technology.EXPRESS_JS]: "Express.js",
  [Technology.FASTIFY]: "Fastify",
  [Technology.NEST_JS]: "Nest.js",
  [Technology.REST]: "REST",
  [Technology.GRAPHQL]: "GraphQL",
  [Technology.TAILWIND_CSS]: "Tailwind CSS",
  [Technology.CAPACITOR]: "Capacitor",
  [Technology.DART]: "Dart",
  [Technology.FLUTTER]: "Flutter",
  [Technology.DOCKER]: "Docker",
  [Technology.GO]: "Go",
  [Technology.CASSANDRA]: "Cassandra",
  [Technology.PROMETHEUS]: "Prometheus",
};

export const iconByTechnology: Record<Technology, string> = {
  [Technology.HTML]: "simple-icons:html5",
  [Technology.CSS]: "simple-icons:css3",
  [Technology.JAVASCRIPT]: "simple-icons:javascript",
  [Technology.TYPESCRIPT]: "simple-icons:typescript",
  [Technology.REACT]: "simple-icons:react",
  [Technology.REACT_NATIVE]: "simple-icons:react",
  [Technology.NEXT_JS]: "simple-icons:nextdotjs",
  [Technology.NODE_JS]: "simple-icons:nodejs",
  [Technology.EXPRESS_JS]: "simple-icons:express",
  [Technology.FASTIFY]: "simple-icons:fastify",
  [Technology.NEST_JS]: "simple-icons:nestjs",
  [Technology.REST]: "dashicons:rest-api",
  [Technology.GRAPHQL]: "simple-icons:graphql",
  [Technology.TAILWIND_CSS]: "simple-icons:tailwindcss",
  [Technology.CAPACITOR]: "simple-icons:capacitor",
  [Technology.DART]: "simple-icons:dart",
  [Technology.FLUTTER]: "simple-icons:flutter",
  [Technology.DOCKER]: "simple-icons:docker",
  [Technology.GO]: "simple-icons:go",
  [Technology.CASSANDRA]: "simple-icons:cassandra",
  [Technology.PROMETHEUS]: "simple-icons:prometheus",
};
